baseURL = 'https://mehmetalierturk.com/'
languageCode = 'en-us'
title = 'Mehmet Ali Erturk'
subtitle = 'Test'
theme = 'loveit'

[params]
  defaultTheme = "auto"

[params.author]
    name = "Mehmet Ali Erturk"
    email = ""
    link = "https://mehmetalierturk.com"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/About/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "publications"
    pre = ""
    post = ""
    name = "Publications"
    url = "/Publications/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""



[params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Mehmet Ali Ertürk, PhD"
      pre = ""
      post = ""
      typeit = false

[params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = ""
      title = ""
      subtitle = ""
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 3

[params.social]
    GitHub = "merturk"
    Linkedin = "merturk"
    twitter = "merturk"
    Medium = "merturk"
    Flickr = "merturk"
    Goodreads = "merturk"
    Googlescholar = "hWKzrncAAAAJ"
    Researchgate = "Mehmet_Ali_Ertuerk"
    ORCID = "0000-0002-4030-1110"
    

[params.page.share]
      enable = false
      X = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Reddit = false
      Instapaper = false
      Pocket = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
  
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "UA-6098617-1"
    respectDoNotTrack = false
    